### ISSUE TITLE
Build fail - draft-wysiwyg\example\browser.js Unexpected token (7:2)

### ISSUE THREAD

**Issue by insekticid** [bkniffler/draft-wysiwyg#13]
```
C:\dev\projects\draft.js\node_modules\draft-wysiwyg>npm run build:example

> draft-wysiwyg@0.2.4 build:example C:\dev\projects\draft.js\node_modules\draft-wysiwyg
> gulp build

(node:20008) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[13:03:30] Using gulpfile C:\dev\projects\draft.js\node_modules\draft-wysiwyg\gulpfile.js
[13:03:30] Starting 'build'...
[13:03:31] [webpack:build-dev] Hash: 4bed3731292b2b3ad3d5
Version: webpack 1.13.2
Time: 158ms
     Asset       Size  Chunks             Chunk Names
    app.js  632 bytes       0  [emitted]  app
app.js.map   95 bytes       0  [emitted]  app
chunk    {0} app.js, app.js.map (app) 28 bytes [rendered]
    [0] multi app 28 bytes {0} [built] [1 error]

ERROR in ./example/browser.js
Module parse failed: C:\dev\projects\draft.js\node_modules\draft-wysiwyg\example\browser.js Unexpected token (7:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (7:2)
    at Parser.pp$4.raise (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExprList (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (C:\dev\projects\draft.js\node_modules\draft-wysiwyg\node_modules\webpack\node_modules\acorn\dist\acorn.js:1741:35)
 @ multi app
[13:03:33] Finished 'build' after 2.41 s
```

C:\dev\projects\draft.js\node_modules\draft-wysiwyg>npm -v
3.10.3

C:\dev\projects\draft.js\node_modules\draft-wysiwyg>node -v
v6.4.0

**Comment by insekticid** [comment]
solved with clean checkout from github instead of npm install draft-wysiwyg, like you said in doc
